### PR TITLE
Implement variant predicates and allele counter

### PR DESCRIPTION
**Pull request by ielis**
Hi @lnrekerle 

I would like to ask you to add implementations to the new `VariantPredicate` and `AlleleCounter` APIs. 

[VariantPredicate](https://github.com/monarch-initiative/genophenocorr/blob/3db1e40bad8e0f792b037513d103c5c4e39895ea/src/genophenocorr/analysis/predicate/genotype/_api.py#L6) tests if a `Variant` meets a certain criterion. For instance, we can test if the `Variant` affects a particular transcript, if it leads to `VariantEffect.MISSENSE_VARIANT`, if it overlaps with exon 5, etc.

[AlleleCounter](https://github.com/monarch-initiative/genophenocorr/blob/3db1e40bad8e0f792b037513d103c5c4e39895ea/src/genophenocorr/analysis/predicate/genotype/_api.py#L27) takes a patient and counts the alleles of all variants that pass a given variant predicate.

I further described the intended logic in the doc strings and there are tests that check the expected output. I would like to ask you to write a reasonable code (no copy-paste stuff) that will make the tests pass.

Please reach out to me if something seems to be missing. Thank you!

### CODE REVIEW

**Comment by lnrekerle** [comment]
@ielis 
In one of the tests for Allele Counter, you have a variant key test that checks for a matching variant key with an expected count of 2. The patient has 2 variants, but only 1 matches the given key. That one variant has two transcripts though. Should we be counting each transcript of a variant as a new variant?

**Comment by lnrekerle** [comment]
Hey @ielis, what is the next step for this PR?

**Comment by ielis** [comment]
Hi @lnrekerle 
I see that you made the tests pass but the `AlleleCounter` implementation is sketchy. Can you please make it right?

**Comment by lnrekerle** [comment]
@pnrobinson Yah I can work on that today!

**Comment by ielis** [comment]
I still need to write some documentation, but this PR is more/less done.

**Comment by ielis** [comment]
Hello @lnrekerle @pnrobinson 

I think this PR is ready for review. Sadly, it is quite a lot of code, but I will explain the main ideas here.

We have a new abstract class [VariantPredicate](https://github.com/monarch-initiative/genophenocorr/blob/790aa33f897495f8b6546008b3b54b84e4b34ab6/src/genophenocorr/analysis/predicate/genotype/_api.py#L7) that tests if a variant passes a criterion (overlaps with exon 9, is a missense variant on a transcript, etc.). We provide out of shelf predicates through [genophenocorr.analysis.predicate.genotype.VariantPredicates](https://github.com/monarch-initiative/genophenocorr/blob/790aa33f897495f8b6546008b3b54b84e4b34ab6/src/genophenocorr/analysis/predicate/genotype/_variant.py#L7).

The predicates can be *combined*. For instance, to test if a variant is a missense variant in exon 9:

```python
from genophenocorr.model import VariantEffect
from genophenocorr.analysis.predicate.genotype import VariantPredicates

missense = VariantPredicates.variant_effect(VariantEffect.MISSENSE, tx_id='NM_123456.7')
nonsense = VariantPredicates.variant_effect(VariantEffect.STOP_GAINED, tx_id='NM_123456.7')
exon9 = VariantPredicates.exon(9, tx_id='NM_123456.7')

missense_or_nonsense_in_exon9 = (missense | nonsense) & exon9
```

We overload Python `&` and `|` operators to build compound predicates.

The variant predicates are used to build predicates for patients:
- compare patients with at least one variant allele vs. patients with no allele (2 groups, previously dominant predicates)
- compare patients with no allele vs. one allele vs 2 alleles (3 groups, previously recessive predicates)
- compare patients with one variant type vs other variant type (2 groups, previously grouping predicates).

I show the example usage in [KBG notebook](https://github.com/monarch-initiative/genophenocorr/blob/variant-predicate/notebooks/ANKRD11/KBG.ipynb) and the API is exemplified in a new section of the user guide [Predicates](https://github.com/monarch-initiative/genophenocorr/blob/variant-predicate/docs/user-guide/predicates.rst). The documentation still needs a little TLC but I will work on that when we are closer to the end of the development.

Please have and look and let me know what you think.
Thanks!

**Review by lnrekerle — COMMENTED** [review]
This looks great to me!

**Pull request merged**
